### ISSUE TITLE
Print progress on 2.4 tft

### ISSUE THREAD

**Issue by susi1508** [teeminus/NoTouchScreenFirmware#11]
I have installed your firmware and with the right klipper config it is working like expected - big thx for that.
Only progress bar stays at 0 percent. I have seen screenshots with values differs from zero. Is print progress working? Board is an BTT skr v1.3

**Comment by teeminus** [comment]
Thats because klipper expects the M73 command to update/show the current print progress: https://github.com/KevinOConnor/klipper/issues/2695#issuecomment-611100591

**Comment by susi1508** [comment]
works. thx for the hint
