### ISSUE TITLE
Choosing the MISO Pin

### ISSUE THREAD

**Issue by Sineos** [teeminus/NoTouchScreenFirmware#25]
First off: v1.3 works nicely on my SKR1.4T with E3 V3 and Klipper 290. Many thanks 👍 

Just for clarification and maybe some additional information for the Wiki:

Initially I had this config:
```
[display]
lcd_type: emulated_st7920
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
```

`spi_software_miso_pin: EXP2_1`, where `EXP2_1` is actually a MISO pin on the EXP header according to the boards schematic.
It works but I thought it could be causing unwanted side-effects when "overwriting" an actual TFT pin with the software SPI implementation.

![grafik](https://user-images.githubusercontent.com/4459312/109639912-154e8680-7b50-11eb-886f-f9125489a95e.png)

So now I changed to:

```
[display]
lcd_type: emulated_st7920
spi_software_miso_pin: P1.24 #NeoPixel Pin
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
en_pin: EXP1_4
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
```

`P1.24` is on the NeoPixel header, which I do not use. It equally works but might be the "cleaner" solution.

**Comment by teeminus** [comment]
Thanks for the suggestion. You could use `EXP1_6` which is the `D4` pin for HD44780 (LCD2004) displays. This pin is dedicated to be used by a display and should therefore be free to use. That's the pin I chose for my miso pin. Could you please try if that works for you as well? If it does I will add both your config and a note on how to choose the miso pin to the wiki.

**Comment by Sineos** [comment]
EXP1_6 works equally fine.

Side question:
Actually I did not really try since I use Klipper' virtual SD feature, but does the SD reader on the TFT work in this environment?

**Comment by teeminus** [comment]
That's what I asked myself. As far as I understood, there is no support for that.

**Comment by teeminus** [comment]
Btw, I updated the Wiki. And closed this issue 😉 

Thanks for beeing a reliable and motivated tester 😄
