### ISSUE TITLE
unable to flash firmware / revert to BT firmware

### ISSUE THREAD

**Issue by cropduster** [teeminus/NoTouchScreenFirmware#38]
Hi there,

I wanted to reflash my TFT35 to BTT firmware, and no mater what SD card or USB stick I choose, it does not flash the firmware. I renamed the .bin to firmware.bin, FIRMWARE.bin and took he original name... nothing works.

**Comment by teeminus** [comment]
Using the original BTT firmware file name should work. Which BTT firmware did you use? 26 oder 27?

**Comment by cropduster** [comment]
Didn't work with BTT 26 either... immediately the splash screen "ST7920Emulator ready" is shown.

**Comment by teeminus** [comment]
What is your flashing procedure?

**Comment by cropduster** [comment]
Sd card in (alternatively: USB stick in) - printer off/on (alternatively: push button on TFT)

**Comment by cropduster** [comment]
...ok, it works now...
