### ISSUE TITLE
Text Upside Down and Backwards.

### ISSUE THREAD

**Issue by TeStevens315** [teeminus/NoTouchScreenFirmware#58]
Not sure what I did wrong but I have my screen working but the text is upside down and backward/mirrored.  The encoder seems to scroll and click fine.     It showed up right after the screen firmware upload before it was connected to Fluidd/klipper, although the interface text didn't show up till connected. 

I have a tft35-e3 v3 connected to a skr 2 rev b.    
I used the precompiled firmware.    

My Klipper config  for the display

[display]
lcd_type: st7920
cs_pin: EXP1_4
sclk_pin: EXP1_5
sid_pin: EXP1_3
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2

Thanks for any help.
Troy

![PXL_20211101_221552906 MP](https://user-images.githubusercontent.com/20211492/139755280-a17cafe8-6fa5-48ef-9982-2b15de85a2ee.jpg)

**Comment by teeminus** [comment]
Thats not an actual issue. Some printer manufacturers flip the screen to mount it 180° rotated (See https://github.com/teeminus/NoTouchScreenFirmware/issues/8). You can manuall recompile the firmware with the following line commented in: https://github.com/teeminus/NoTouchScreenFirmware/blob/63a382f294762900353005e41adb902b55045938/src/User/features.h#L11
