### ISSUE TITLE
TFT35 V3 + Skr 1.4 Turbo correcct values

### ISSUE THREAD

**Issue by gitxmax** [teeminus/NoTouchScreenFirmware#65]
Not an issue, but rather a correction..
Tried connecting my 1.4 Turbo with TFT35 V3 screen, as per the template posted here and it was giving me an error, the values below worked for me ..

![image](https://user-images.githubusercontent.com/34851333/178141004-4f79c346-9733-4413-bda3-163d83467cea.png)

`

**Comment by teeminus** [comment]
Thanks for your feedback. What error do you get?

**Comment by gitxmax** [comment]
Sorry, can't insert the correct code, github drops some characrers .. Guess same issue with the original poster ..

**Comment by teeminus** [comment]
Maybe a screenshot will work?

**Comment by gitxmax** [comment]
![image](https://user-images.githubusercontent.com/34851333/178140693-9cc9ae11-57b4-4145-a501-9f323c064729.png)

**Comment by teeminus** [comment]
What error message did you get?

**Comment by gitxmax** [comment]
It works fine as with the screenshot I provided, no errors. The template in your readme is also missing the line endings .. yu can check ..
Interesting thing, without the screen, my klipper was constantly disconnecting from the mcu, with the screen connected, the connection keeps up stable ..

**Comment by teeminus** [comment]
I will do and correct the wiki. Thanks for your feedback 👍
