### ISSUE TITLE
Changing the font

### ISSUE THREAD

**Issue by mbgroot** [teeminus/NoTouchScreenFirmware#7]
Is it possible to change the font? I made a Terminus font for the Klipper (https://raw.githubusercontent.com/mbgroot/klipper/master/klippy/extras/display/font8x14.py) but it doesn't work with this screen firmware.
i use TFT24_v11 - firmware work fine.

**Comment by teeminus** [comment]
Short answer: Depends on the font. The "buildin" ST7920 font won't be changed, the font used by klipper on the status screen is part Klipper and would have to be changed there.

Long answer:
There are two types of font. The first one is the 8x16 which is part of the ST7920 (which is shown in the ST7920 datasheet and emulated by the ST7920 emulator) and the second one is the font used by Klipper in the graphics mode.

The first font is mainly used for the menu, the second one is used on the graphical status screen. So the first font can't be changed as it would make the emulator behave different than the real display. The second font is not part of this project and would have to be changed in the klipper project.
