### ISSUE TITLE
MKS Robin TFT35(FSMC)

### ISSUE THREAD

**Issue by iMarkus** [teeminus/NoTouchScreenFirmware#70]
Hi,
thanks for your great work.

Do you think that this might also work for the MKS Robin TFT35(FSMC) which comes with the TwoTrees Bluer printer. 

## Machine Specs
| Parameter | Value |
|--|--|
Number of nozzles|1|
Construction volume|235mm * 235mm * 280mm|
Printing method|SD-Card / online printing (by Serial UART communication through printer USB connector and some internet interface)|
IHM|3.5 inch color touch screen|
Machine speed|10~300mm/s|
Print speed|20~200mm/s|
Extrusion head temperature (highest)|260 °C|
Maximum hot bed temperature (highest)|100 °C|
Printing platform|Warm bed|
XY axis positioning accuracy|0.01mm|
Z axis positioning accuracy|0.004mm|
Recommended printed material|PLA, ABS and PETG|
Consumable filament diameter|1.75mm|
Print file format|G-Code|
Machine size|L=410mm * W=400mm * H=520mm|
Machine weight|7.5kg|
Power supply|127V~220V/240W|
Microcontroller|[STM32F103VET6 datasheet](https://github.com/TiagoPaulaSilva/Two-Trees-Bluer-3D-Printer/blob/master/Hardware/Motherboard/2.%20Datasheets/MCU/STM32F103VET6.pdf)|
Motor Driver|[TMC2209 datasheet](https://github.com/TiagoPaulaSilva/Two-Trees-Bluer-3D-Printer/blob/master/Hardware/Motherboard/2.%20Datasheets/Stepper%20Motor%20Driver/TMC2209.pdf)|
Stepper Motor|[US-17HS4401S datasheet](https://github.com/TiagoPaulaSilva/Two-Trees-Bluer-3D-Printer/blob/master/Hardware/Stepper%20Motors/US-17HS4401S.pdf)|
Motherboard|[MKS Robin Nano v1.2 schematic](https://github.com/TiagoPaulaSilva/Two-Trees-Bluer-3D-Printer/blob/master/Hardware/Motherboard/1.%20Schematic/MKS%20Robin%20Nano%20v1.2.pdf) ([source HW + FW](https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X))|
Display|MKS Robin TFT35(FSMC) (schematic not available)|

More information on the manufacturer's official website: https://twotrees3d.com/

## Reference
https://github.com/TiagoPaulaSilva/Two-Trees-Bluer-3D-Printer

**Comment by teeminus** [comment]
I‘m sorry, but I have no idea. I don’t even know if the MKS displays listed in the readme do work.
