### ISSUE TITLE
Custom menu?

### ISSUE THREAD

**Issue by bkenobi** [teeminus/NoTouchScreenFirmware#73]
I just installed v1.3.1 on my TFT35 V3.0 and it works great!  I tried the BTT firmware and it was so glitchy I almost removed the screen.  The only thing that I can't seem to do that would be really handy is a way to shut down my RPi from the display.  Since my RPi is powered via a buck converter off the printer's PSU, I have to use a computer/tablet/phone to log in to OctoPrint or SSH to the RPi and send a halt command.  If there was a way to send that one command, I'd be able to safely shut down without needing another device.

Either way, this is a great contribution.  Thanks!

**Comment by teeminus** [comment]
I am sorry, the firmware is driven completely by the printer. All menus are from your printer firmware. If you are using Klipper you might be lucky as custom menus and menu entries can be configured in your printer.cfg. But I am not sure if you can execute system commands from there.
